# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: VMhost

steps:
- task: SSH@0
  inputs:
    # Create ssh connection for the VM.
    sshEndpoint: 'intanceAgent'
    runOptions: 'inline'
    inline: |
      git clone https://github.com/yarined/arm.git
      cd arm
      sh blob_migration.sh
      cd .. && rm -r arm
    readyTimeout: '20000'