# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1(b60b97f4-3bd0-4618-b436-c337986be64c)'
    subscriptionId: 'b60b97f4-3bd0-4618-b436-c337986be64c'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'arm'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: 'storageAccount.json'
    deploymentMode: 'Incremental'
    deploymentName: 'CreateStorageAccount'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1(b60b97f4-3bd0-4618-b436-c337986be64c)'
    subscriptionId: 'b60b97f4-3bd0-4618-b436-c337986be64c'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'arm'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: 'linuxVM.json'
    deploymentMode: 'Incremental'
    deploymentName: 'CreateVM'