# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

# Created selfhost and called him Default
pool:
  name: Default

steps:
- task: SSH@0
  inputs:
    sshEndpoint: 'intanceAgent'
    runOptions: 'inline'
    inline: |
      git clone https://github.com/yarined/arm.git
      cd arm
      sh blob_migration.sh
    readyTimeout: '20000'